### PR TITLE
Cesium view polyline

### PR DESCRIPTION
**Pull request by nickgaray**
Updated Cesium view to support polylines in same manner as MapView based components.  Made some minor updates to clean code analysis messages.

Kept new layer development separate for now to minimize impact to osh-js.

### CODE REVIEW

**Comment by mdhsl** [comment]
I had to fix several things to make it work:

1) there was a problem in the method updating the polyline position, indeed, cesium is waiting for a cartesian array while you were returning the default position { x: .., y:: .., z: ...}:

https://cesium.com/docs/cesiumjs-ref-doc/Entity.html?classFilter=ENtity#polyline

https://cesium.com/docs/cesiumjs-ref-doc/PositionProperty.html

Did it work in your examples? Because without this change, the polyline was not displayed in the 2 examples I created.

2) You were using the Layer to get the position by doing: "polylineLayer.props.locations.polyline".

Now, each location, and this is also true for markers, is dependent on a 'polylineId' or 'markerId'; this allows to use several polylines associated with one single layer (see the AVL demo). For this purpose, we need to reuse this property to make sure that each polyline is displayed in the right place according to its id.

3) I added a demo in the showcase to demonstrate how polyline works in a simple example of cesium

4) I added the polylineLayer in the AVL demo (which demonstrated the polylineId problem)

5) I added a property to define if the polyline must be clamped on the property

**Comment by mdhsl** [comment]
Another thing, you use callback property to update the polyline. It means that even if the polyline hasn't changed, it is always recalculated (I seems at the refresh rate of the globe). 
I have the impression that this is not really optimal, because in addition we have to translate the x,y,z coordinates into cesium cartesian coordinates. 
Isn't there another way?

**Comment by nickgaray** [comment]
The layer which is using this code is:

/**

 Creates a line of bearing Styler
 */
class LineOfBearingLayer extends Layer {

    /**
     *

     @param properties
     */
    constructor(properties) {
        super(properties);
        this.type = 'polyline';
        this.properties = properties;
        this.props.locations = [];
        this.props.color = 'red';
        this.props.width = 1;
        this.props.opacity = 1;
        this.props.smoothFactor = 1;
        this.props.polylineId = 'polyline';

        if (hasValue(properties.color)) {
            this.props.color = properties.color;
        }

        if (hasValue(properties.width)) {
            this.props.width = properties.width;
        }

        if (hasValue(properties.opacity)) {
            this.props.opacity = properties.opacity;
        }

        let that = this;

        if (this.checkFn("getLocations")) {
            let fn = function(rec, timeStamp, options) {
                let locations = that.getFunc('getLocations')(rec, timeStamp, options);
                if(!(that.props.polylineId in that.props.locations)) {
                    that.props.locations[that.props.polylineId] = [];
                }
                if (that.props.locations[that.props.polylineId].length === 2) {
                    that.props.locations[that.props.polylineId].shift();
                    that.props.locations[that.props.polylineId].shift();
                }
                that.props.locations[that.props.polylineId].push(...locations);
            };
            this.addFn(that.getDataSourcesIdsByProperty('getLocations'),fn);
        }
    }

    /**
     *
     */
    clear() {
        this.props.locations[this.props.polylineId] = [];
    }
}

While the respective getLocations function invoked is:

        this.polylineProperties.getLocations = {
            dataSourceIds: [dataSource.getId()],
            handler: (rec) => {

                    let locationArray = [];

                    let bearing = rec['raw-lob'] * Math.PI / 180;

                    let startLat = rec[path].lat * Math.PI / 180;
                    let startLon = rec[path].lon;
                    if (startLon < 0) {
                        startLon = (360 + startLon) * Math.PI / 180;
                    }
                    let startHeight = rec[path].alt;
                    let startPos = {
                        lat: startLat,
                        lon: startLon,
                        alt: startHeight
                    };
                    let distance = 10;
                    let R = 6371;

                    let endLat = Math.asin(Math.sin(startPos.lat) * Math.cos(distance / R) + Math.cos(startPos.lat) * Math.sin(distance / R) * Math.cos(bearing));
                    let endLon = startPos.lon + Math.atan2(Math.sin(bearing) * Math.sin(distance / R) * Math.cos(startPos.lat), Math.cos(distance / R) - Math.sin(startPos.lat) * Math.sin(endLat));
                    let endHeight = startHeight;
                    let endPos = {
                        lat: endLat,
                        lon: endLon,
                        alt: startHeight
                    };
                    let cartOrig = Cesium.Cartesian3.fromRadians(startPos.lon, startPos.lat, startPos.alt);
                    let cartEnd = Cesium.Cartesian3.fromRadians(endPos.lon, endPos.lat, endPos.alt);

                    locationArray.push(cartOrig);
                    locationArray.push(cartEnd);
                    return locationArray;
                }
        };

Which is calculating a start and end position.  In this case the need to update with the Cesium CallbackProperty is needed since the LoB is a vector, given by the source start position and in this case for simplicity, a static magnitude and the bearing received from the record.  So it needs to update continouosly with the refresh rate of the globe.  The sensor generating this data is mobile  and tracking the source of a signal.  If the sniffer or the target move the LoB characteristics change (start & end points).

**Comment by nickgaray** [comment]
Alex had asked me to keep the Layer seperate instead of placing it within osh-js at present.

**Comment by alexrobin** [comment]
I think the `LineOfBearingLayer` has to be completely decoupled from the `PolylineLayer`. It's not at all the same thing even if in both cases we draw lines on the screen.

I agree with @mdhsl that the data that is returned by the `PolylineLayer.getLocations()` function should be lat/lon, just like for markers so it means the view needs to convert it as appropriate.

**Comment by alexrobin** [comment]
@nickgaray you can update Cesium geometries whenever the data changes without using a `CallbackProperty` by the way

**Comment by nickgaray** [comment]
> I think the `LineOfBearingLayer` has to be completely decoupled from the `PolylineLayer`. It's not at all the same thing even if in both cases we draw lines on the screen.

Ok, I understand now the need to keep separate.   

> I agree with @mdhsl that the data that is returned by the `PolylineLayer.getLocations()` function should be lat/lon, just like for markers so it means the view needs to convert it as appropriate.

Will make these changes.

**Comment by mdhsl** [comment]
> Alex had asked me to keep the Layer seperate instead of placing it within osh-js at present.

Ha ok, I did not test the right thing. I was confused by https://github.com/opensensorhub/osh-js/blob/cesium_view_polyline/source/osh/ui/view/map/CesiumView.js#L99

If this layer is a separate one, you have to use separate keyword like 'polylineBearing' as well as the methods as I did with imageDraping for example because you have used the same method:

updatePolyline()
addPolyline
addPolylineToLayer()
..

This is not a problem, I did make it work for simple polyline for now, yours is slightly different

**Comment by mdhsl** [comment]
Moreover, I don't find any PolylineOfBearing class in the source code, neither in osh-est, nor osh directory. Can you point to me the location of this file?

**Comment by nickgaray** [comment]
@mdhsl since I was asked to keep it outside osh-js for the time being I created it as part of our project, however here is the source.  Notice I kept _type='polyline'_ otherwise I would have to have made changes to MapView.js to support 'polylineBearing' in case to call updatePolyline.

/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are subject to the Mozilla Public License, v. 2.0.
 If a copy of the MPL was not distributed with this file, You can obtain one
 at http://mozilla.org/MPL/2.0/.

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 for the specific language governing rights and limitations under the License.

 Copyright (C) 2021 Botts Innovative Research, Inc. All Rights Reserved.

 Author: Nicolas Garay <nic.garay@botts-inc.com>

 ******************************* END LICENSE BLOCK ***************************/
import Layer from "osh/ui/layer/Layer.js";
import { hasValue } from "osh/utils/Utils.js";

/**

 Creates a line of bearing Styler
 */
class LineOfBearingLayer extends Layer {

    /**
     *

     @param properties
     */
    constructor(properties) {
        super(properties);
        this.type = 'polyline';
        this.properties = properties;
        this.props.locations = [];
        this.props.color = 'red';
        this.props.width = 1;
        this.props.opacity = 1;
        this.props.smoothFactor = 1;
        this.props.polylineId = 'polylineBearing';

        if (hasValue(properties.color)) {
            this.props.color = properties.color;
        }

        if (hasValue(properties.width)) {
            this.props.width = properties.width;
        }

        if (hasValue(properties.opacity)) {
            this.props.opacity = properties.opacity;
        }

        let that = this;

        if (this.checkFn("getLocations")) {
            let fn = function(rec, timeStamp, options) {
                let locations = that.getFunc('getLocations')(rec, timeStamp, options);
                if(!(that.props.polylineId in that.props.locations)) {
                    that.props.locations[that.props.polylineId] = [];
                }
                if (that.props.locations[that.props.polylineId].length === 2) {
                    that.props.locations[that.props.polylineId].shift();
                    that.props.locations[that.props.polylineId].shift();
                }
                that.props.locations[that.props.polylineId].push(...locations);
            };
            this.addFn(that.getDataSourcesIdsByProperty('getLocations'),fn);
        }
    }

    /**
     *
     */
    clear() {
        this.props.locations[this.props.polylineId] = [];
    }
}

export default LineOfBearingLayer;

**Comment by nickgaray** [comment]
@mdhsl I am now having issue where polyline is not visible, if it is rendering.  I have traced down into Cesium and am not seeing issues that would cause line of bearing to not render

**Comment by mdhsl** [comment]
> @mdhsl I am now having issue where polyline is not visible, if it is rendering. I have traced down into Cesium and am not seeing issues that would cause line of bearing to not render
> 
> This is how I am computing start and endpoints for line of bearing as x,y,z (lat, lon, alt) tuples
> 
> ```
>     this.polylineProperties.getLocations = {
>         dataSourceIds: [dataSource.getId()],
>         handler: (rec) => {
> 
>                 let locationArray = [];
> 
>                 let bearing = rec['raw-lob'] * Math.PI / 180;
> 
>                 let startPosRadians = {
>                     lat: rec[path].lat * Math.PI / 180,
>                     lon: (rec[path].lon < 0) ? (360 + rec[path].lon) * Math.PI / 180 : rec[path].lon,
>                     alt: rec[path].alt
>                 };
> 
>                 let distance = 10;
>                 let R = 6371;
> 
>                 let endLatRadians = Math.asin(Math.sin(startPosRadians.lat) * Math.cos(distance / R) + Math.cos(startPosRadians.lat) * Math.sin(distance / R) * Math.cos(bearing));
>                 let endLonRadians = startPosRadians.lon + Math.atan2(Math.sin(bearing) * Math.sin(distance / R) * Math.cos(startPosRadians.lat), Math.cos(distance / R) - Math.sin(startPosRadians.lat) * Math.sin(endLatRadians));
> 
>                 let cartesianEnd = Cesium.Cartesian3.fromRadians(endLonRadians, endLatRadians, rec[path].alt);
> 
>                 let cartographicEnd = Cesium.Cartographic.fromCartesian(cartesianEnd);
> 
>                 // Push the start position
>                 locationArray.push({
>                         x: rec[path].lat,
>                         y: rec[path].lon,
>                         z: rec[path].alt,
>                     });
> 
>                 // Push the end position
>                 locationArray.push({
>                         x: Cesium.Math.toDegrees(cartographicEnd.latitude),
>                         y: Cesium.Math.toDegrees(cartographicEnd.longitude),
>                         z: rec[path].alt,
>                     });
> 
>                 return locationArray;
>             }
>     };
> ```

Thats normal, because you transform the coordinates into the Layer and I have made something to transform the coordinate into the View. Like Alex said, it is better to let the view doing this job.

Moreover, you have to define new methods in Cesium  to support bearing if it is different from the simple Polyline

**Comment by nickgaray** [comment]
Updated line of bearing layer, do we want this in osh-ext? 


```
/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are subject to the Mozilla Public License, v. 2.0.
 If a copy of the MPL was not distributed with this file, You can obtain one
 at http://mozilla.org/MPL/2.0/.

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 for the specific language governing rights and limitations under the License.

 Copyright (C) 2021 Botts Innovative Research, Inc. All Rights Reserved.

 Author: Nicolas Garay <nic.garay@botts-inc.com>

 ******************************* END LICENSE BLOCK ***************************/
import Layer from "osh/ui/layer/Layer.js";
import {hasValue, randomUUID} from "osh/utils/Utils.js";

/**

 Creates a line of bearing Styler
 */
class LineOfBearingLayer extends Layer {

    /**
     *

     @param properties
     */
    constructor(properties) {
        super(properties);
        this.type = 'polyline';
        this.properties = properties;
        this.props.locations = [];
        this.props.color = 'red';
        this.props.weight = 1;
        this.props.opacity = 1;
        this.props.smoothFactor = 1;
        this.props.polylineId = 'bearingLine-' + randomUUID();

        if (hasValue(properties.color)) {
            this.props.color = properties.color;
        }

        if (hasValue(properties.width)) {
            this.props.weight = properties.width;
        }

        if (hasValue(properties.opacity)) {
            this.props.opacity = properties.opacity;
        }

        let that = this;

        if (this.checkFn("getLocations")) {
            let fn = function(rec, timeStamp, options) {
                let locations = that.getFunc('getLocations')(rec, timeStamp, options);
                if(!(that.props.polylineId in that.props.locations)) {
                    that.props.locations[that.props.polylineId] = [];
                }
                if (that.props.locations[that.props.polylineId].length === 2) {
                    that.props.locations[that.props.polylineId].shift();
                    that.props.locations[that.props.polylineId].shift();
                }
                that.props.locations[that.props.polylineId].push(...locations);
            };
            this.addFn(that.getDataSourcesIdsByProperty('getLocations'),fn);
        }
    }

    /**
     *
     */
    clear() {
        this.props.locations[this.props.polylineId] = [];
    }
}

export default LineOfBearingLayer;
```

**Comment by nickgaray** [comment]
It is working!

image

**Pull request merged**
