### PR TITLE
Styler add callback to styler #291 v2

### PR DESCRIPTION
**Pull request by mdhsl**

### CODE REVIEW

**Comment by mdhsl** [comment]
Issue demonstration: http://opensensorhub.github.io/osh-js/v2.0.0/Issues/291

**Comment by alexrobin** [comment]
Cool, good job on this PR.

My comments:
- It would be good that the Cesium view also reports pixel coordinates so one can use it to display a popup menu at the cursor location
- Disable the popup in Leaflet by default (at least when an onClick callback is set)
- Icons disappear in the OL view when I click on them sometimes
- Mike asked if you could put more inline comments in the demo examples since they are meant to be used for teaching.
- Can right click be easily supported as well? If it is, then an example with a custom context menu would be useful

**Comment by mdhsl** [comment]
For leaflet, you mean the tooltip or the popup?
Actually, the tooltip display the label and the popup display the name & description if the name and description are provided.

**Comment by mdhsl** [comment]
- Cesium view reports pixel coordinates so one can use it to display a popup at the cursor location: ba9d95f2
- disable the popup in Leaflet by default (at least when an onClick callback is set): d7b3a5ee
- Fix wrong onHover OL Styler callback: bd11fd2a

Moreover, I had to change Cesium & OL select implementation because it was not correct. 

For Cesium, it was done in the updateMarker method and took the current Styler, which doesn't make sense because it doesn't match the styler when selecting a given marker.

For OL, I used the interactions provided by OL, which is more adapted and efficient: https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select.html

In any case, I also removed the fact of launching an event even when the marker was undefined. I now only launch events when the marker is defined.

**Comment by mdhsl** [comment]
Example has been moved: http://opensensorhub.github.io/osh-js/dev/Issues/291/avl.html

**Comment by alexrobin** [comment]
Looking good for the 3 first bullets, thanks. 
Have you given some thoughts about my last question regarding catching right clicks?

**Comment by mdhsl** [comment]
Done in last commit: 92524069fb3b4045a9e3aef4b976d7aab7607b29 ~ 6959239664ff1cb915c80099c6dcb4a02eda76be

**Pull request merged**
